### PR TITLE
add modules to manage automount management in ipa

### PR DESCRIPTION
**Pull request by chr15p**
This adds modules to manage the three components of automount maps as used by freeipa,  locations, maps and keys.

### CODE REVIEW

**Comment by t-woerner** [comment]
@chr15p Please use one PR per module.

**Comment by chr15p** [comment]
@t-woerner I can break it up if you prefer but in my opinion the modules dont make a huge amount of sense independently, automount location for example is just a container within freeipa to hold automountmaps, which are inturn just a container within automount for the real functionality, the automountkeys which cant exist outside of the two containers.

So its your choice, I can break them up if you want but merging one without the other two wouldn't be super useful.

**Comment by rjeffman** [comment]
@chr15p I also prefer that each module has its PR.

As they are only management interfaces, it doesn't really matter if one is merged before the other. What would be better, and I believe that it will happen anyway, is that they are released together.

**Comment by chr15p** [comment]
see PR's 496, 497 and 498  as replacements for this one

**Comment by rjeffman** [comment]
Thank you @chr15p!

**Pull request closed without merging**
