### PR TITLE
ipauser: Support for External IdP attributes.

### PR DESCRIPTION
**Pull request by rjeffman**
Add support for 'idp' and 'idp_user_id' to ipauser plugin.

FreeIPA 4.10.0 is required for both attributes.

### CODE REVIEW

**Comment by rjeffman** [comment]
There's still an issue with "timing" on the tests, as the command to create the IDP entry is not working when executed inside the testing container, but always succeed in a clean CentOS 9 Stream VM.

**Comment by rjeffman** [comment]
It was not timing after all...

The `idp-add` command now has a test to verify if the `idp` object exists, and tests are passing.

**Comment by t-woerner** [comment]
idp and idp_user_id parameters are not in the spec anymore.

**Comment by rjeffman** [comment]
@t-woerner PR is ready for review again.

**Review by varunmylaraiah — APPROVED** [review]
LGTM.
Existing downstream tests have been successfully passed.

**Pull request merged**
