### PR TITLE
module_params_get*: Fail on empty string in string list parameters

### PR DESCRIPTION
**Pull request by t-woerner**
So far it is possible to pass list parameters with empty strings to the
modules. The use of empty strings in list does not make a lot of sense,
though. The simple solution is to add a check to module_params_get for
empty strings in returned lists.

module_params_get_lowercase has been changed to use module_params_get to
have one place to add the check.

### CODE REVIEW

**Review by varunmylaraiah — COMMENTED** [review]
Triggered Downstream tests with this PR https://gitlab.cee.redhat.com/mvarun/trigger-tool/-/pipelines/1722057

**Comment by varunmylaraiah** [comment]
@t-woerner 
Still, Changes require for 
1) Config Module : pac_type and auth_type
2) Service Module: pac_type
3) User Module : sshpubkey
4) Automount Module : empty description

**Comment by rjeffman** [comment]
This PR would no fix this issue:
>     4. Automount Module : empty description.

See PR #754 which is a draft that aims to fix this specific issue.

**Review by rjeffman — APPROVED** [review]
LGTM.

**Comment by varunmylaraiah** [comment]
LGTM

**Review by varunmylaraiah — APPROVED** [review]

**Pull request merged**
