### PR TITLE
Vault add state retrieved

### PR DESCRIPTION
**Pull request by rjeffman**
Add state `retrieved` to ipavault to retrieve vault stored data.
    
    This patch adds support for retrieving data stored in an IPA vault by
    adding a new valid state for ipavault: `retrieved`.
    
    To allow the retrieval of data from assymetric vaults, the attributes
    `private_key`, `private_key_files` and `out` were also added to the
    module.
    
    The private key files, `private.pem`, should be paired with the already
    existing `public.pem` public key files.
    
    Tests were updated to reflect changes and two new playbooks were added:
    
        playbooks/vault/retrive-data-asymmetric-vault.yml
        playbooks/vault/retrive-data-symmetric-vault.yml

### CODE REVIEW

**Comment by varunmylaraiah** [comment]
Hi @rjeffman,
Are you going to add support for password-file(File containing the vault password)?

**Comment by rjeffman** [comment]
The support for password-files are on another PR #263, and retrieving vault data (that deals with private key files) is on PR #275. None of them is merged, yet.

**Comment by varunmylaraiah** [comment]
@rjeffman 
Few variables are missing in README-vault.md
owners,
ownergroups,
ownerservices,
vault_password_file

**Comment by varunmylaraiah** [comment]
The test is missing for ownerservices.

**Comment by rjeffman** [comment]
@varunmylaraiah, thanks for reviewing. I fixed the issues highlighted.

**Pull request merged**
