### PR TITLE
Added Debian support for ipaclient

### PR DESCRIPTION
**Pull request by Uumas**
Simply added the same ipaclient package as already used on ubuntu. Debian doesn't support server yet.

### CODE REVIEW

**Comment by t-woerner** [comment]
Thanks for opening this. Please also add the files for ipaserver and ipareplica roles. I think it should be similar to the Ubuntu files. But the package for trust ad is missing there.

**Comment by Uumas** [comment]
There are no server packages for Debian: https://packages.debian.org/search?keywords=freeipa&searchon=names&suite=all&section=all

**Comment by t-woerner** [comment]
Please split this pull request into smaller pieces. Debian changes and OTP changes should not be mixed. BTW: I already had a patch for the dnsok assigment issue: https://github.com/freeipa/ansible-freeipa/commit/743216b0db239fcebaa0403e20deea00e3cd5d57

**Comment by Uumas** [comment]
Oh, didn't realize it would appear in this same commit, just learning to use git. I'll close this and make a new request from a specific branch.

**Pull request closed without merging**
