### PR TITLE
Added support for predefining client OTP using ipaclient_otp

### PR DESCRIPTION
**Pull request by Uumas**
Allows predefining otp for ipaclient role using variable ipaclient_otp

### CODE REVIEW

**Comment by t-woerner** [comment]
Can't this simply be achieved also by setting ipaadmin_password to the already generated OTP for the client?

**Comment by Uumas** [comment]
It would try to use that password to get the otp from the ipaserver then.

**Comment by t-woerner** [comment]
Set ipaadmin_password without ipaclient_get_otp. For client this should be the same.

Only for replica installations this will not be working. But the use of _get_otp for replica is something that I might remove again as a normal password is needed either way.

**Comment by Uumas** [comment]
Sorry for taking so long to test this, but anyway. 
Using otp for ipaadmin_password causes this error:
```
< TASK [freeipa.ipaclient : Install - Join IPA] >
 -----------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [<hostname>]: FAILED! => {"changed": false, "msg": "Kerberos authentication failed: kinit: Password incorrect while getting initial credentials\n"}
```
It seems ipaclient_use_otp needs to be set to yes for it to work, but without this commit it would try to get a new otp if it is set to yes.

**Comment by djasa** [comment]
Just tested this. Works as expected both when client is joined and when it is not (turning role off with default `ipaclient_allow_repair: False` and just to configuration modification with it set to True):
```yaml
    - name: IPA join - try to get password locally using default ccache
      ipa_host:
        ipa_host: "{{ ipa_host }}"
        ipa_user: "{{ ipa_user }}"
        fqdn: "{{ inventory_hostname }}"
        random_password: True
      delegate_to: localhost
      register: ipa_host
      ignore_errors: true

    - name: IPA join - join and configure
      include_role:
        name: ipaclient
      vars:
        state: present
        ipaclient_domain: "{{ ipa_domain }}"
        ipaclient_realm: "{{ ipa_realm }}"
        ipaclient_otp: "{{ ipa_host.host.randompassword | default(omit) }}"
        # other vars
```

**Comment by t-woerner** [comment]
Thanks for the enhancement

**Pull request merged**
