### PR TITLE
Use ansible_facts variable

### PR DESCRIPTION
**Pull request by xek**
On an environment with inject facts disabled, the "Import variables specific to distribution" task fails with "Could not find file on the Ansible Controller..."

### CODE REVIEW

**Comment by xek** [comment]
See more error output here: https://bugs.launchpad.net/tripleo/+bug/1919064

**Comment by rjeffman** [comment]
The "Verify Ansible documentation" check can be ignored. It will be fixed once PR #515 is merged.

**Review by rjeffman — CHANGES_REQUESTED** [review]
Thank you for the contribution.

Although I'm fine with the changes, this change should also be applied on the other roles, and on tests and example playbooks. In my opinion, we should be consistent on accessing Ansible facts throughout the code.

**Comment by xek** [comment]
@rjeffman  ack, I applied the change to other roles and modified tests/ansible.cfg

**Review by rjeffman — CHANGES_REQUESTED** [review]
LGTM.

**Comment by rjeffman** [comment]
Once commit message is changed, this PR can be merged.

**Review by rjeffman — APPROVED** [review]

**Pull request merged**
