### PR TITLE
fix for nonposix and external group settings

### PR DESCRIPTION
**Pull request by RobVerduijn**
the ipagroup.py module compares only key values\
the external and nonposix settings are net returned as a key in find_res when the group is found,\
 but as a part of the list in the objectclass key.

when a group is a posix group the objectclass list contains the string 'posixgroup'.\
when a groups is a nonposix group the objectclass list does not contain the string 'posixgroup'.\
when a group is external the objectclass list contains the string 'ipaexternalgroup'.\
when a group is an external group the objectclass list does not contain the string 'posixgroup'.

Rob

### CODE REVIEW

**Comment by RobVerduijn** [comment]
@t-woerner @rjeffman please review

**Comment by rjeffman** [comment]
@RobVerduijn, thanks for the changes, but there are a few problems that your modifications just partially address, and should be fixed along with these changes.

When a group is added, by default it is a POSIX group, and such group cannot be made external, also, it cannot be changed back to a non-POSIX group.

If a non-POSIX group is created, than it can later be changed to be a POSIX group or an external group. Converting the group to external is currently supported by ansible-freeipa, but changing the non-POSIX group to POSIX is not supported (but should, as is done in the CLI).

This should all be addressed together to fix the external/nonposix/posix group issues.

**Comment by RobVerduijn** [comment]
> @RobVerduijn, thanks for the changes, but there are a few problems that your modifications just partially address, and should be fixed along with these changes.
> 
> When a group is added, by default it is a POSIX group, and such group cannot be made external, also, it cannot be changed back to a non-POSIX group.
> 
> If a non-POSIX group is created, than it can later be changed to be a POSIX group or an external group. Converting the group to external is currently supported by ansible-freeipa, but changing the non-POSIX group to POSIX is not supported (but should, as is done in the CLI).
> 
> This should all be addressed together to fix the external/nonposix/posix group issues.

mmm...interesting use of the posix and nonposix setting with ipa group-mod.

I fixed it so that now it is consistent with the use of ipa group-add and ipa group-mod

* a nonposix group can be created with group-add
* an external group can be created with group-add
* a nonposix group can be changed to a posix group with group-mod
* a nonposix group can be changed to an external group with group-mod
* an external group cannot be changed to a posix group with group-mod
* an external group cannot be changed to a nonposix group with group-mod
* it will no longer break if you run your play multiple times (it is now idempotent)
Rob

**Comment by rjeffman** [comment]
@RobVerduijn, your PR showed that there was a missing attribute (`posix`) that should be supported by ansible-freeipa. I've opened a new PR fix both the problem you spotted, and adds the missing attribute.

Thanks for raising this issue!

**Comment by rjeffman** [comment]
@RobVerduijn, please review PR #327.

**Comment by RobVerduijn** [comment]
ah wel, as long as it get's fixed

Cheers

**Pull request closed without merging**
