### PR TITLE
[WIP] ipaclient: Configure DNS resolver

### PR DESCRIPTION
**Pull request by t-woerner**
Optionally configure global DNS resolver NetworkManager, systemd-resolved
or /etc/resolv.conf within ipaclient_test.

The configuration of NetworkManager, systemd-resolved and /etc/resolv.conf
is done in the same way as on the initial master. For NetworkManager the
file '/etc/NetworkManager/conf.d/zzz-ipa.conf' will be generated, for
system-resolved '/etc/systemd/resolved.conf.d/zzz-ipa.conf'.

New functions in ansible_ipa_client:

- configure_dns_resolver
  Configures global DNS resolver NetworkManager, systemd-resolved or
  /etc/resolv.conf

- unconfigure_dns_resolver
  Reverts global DNS resolver configuration

New parameters for the role:

- ipaclient_configure_dns_resolver
  The bool value defines if the DNS resolver will be configured.
  NetworkManager and systemd-resolved will be configured if enabled else
  /etc/resolv.conf will be adapted. `ipaclient_configure_dns_resolver`
  defaults to `no`

- ipaclient_dns_servers
  List of DNS servers to use if `ipaclient_configure_dns_resolver` is
  enabled. If `ipaclient_dns_servers` is not defined, the list will be
  generated from `ipaclient_servers` or `ipaservers` group.

- ipaclient_dns_domain_name
  List of DNS search domain names to use if
  `ipaclient_configure_dns_resolver` is enabled. if
  `ipaclient_dns_domain_names` the list will be generated using the domain
  name.

---
This PR depends on changes from PR #643 (ipaclient_setup_nss: Use proper nosssd_files list)

### CODE REVIEW

**Review by fcami — COMMENTED** [review]
I don't think we should ever activate systemd-resolved for reasons detailed [there](https://lists.freedesktop.org/archives/systemd-devel/2021-September/046856.html).

On clients its performance is less than optimal.
On servers, this breaks IPA's DNS zone detection.

Plus, it is not clear when systemd-resolved will be supported in any enterprise distribution.

**Comment by rjeffman** [comment]
Shouldn't this be carried out by something like [Network Linux System Role](https://github.com/linux-system-roles/network)?

Also, does this work with Ubuntu's `netplan`?

**Comment by rjeffman** [comment]
Shouldn't this be carried out by something like [Network Linux System Role](https://github.com/linux-system-roles/network)?

Also, does this work with Ubuntu's `netplan`?

**Comment by t-woerner** [comment]
As soon as the change in freeipa has been done, I will also drop the code for system-resolved.

**Comment by rjeffman** [comment]
This PR has been replaced by #988, which was already merged.

**Pull request closed without merging**
