### PR TITLE
Fix service tests.

### PR DESCRIPTION
**Pull request by rjeffman**
This PR fixes tests for the ipaservice module that failed in some testing environments.

### CODE REVIEW

**Comment by varunmylaraiah** [comment]
Thank you for the PR. Changes LGTM.

**Comment by rjeffman** [comment]
Rebased.

**Comment by seocam** [comment]
One thing caught my attention in this PR: many strings are enclosed by double quotes. Is that really needed?
I can see it's not only code modified by this PR but in the services tests as a whole. 

Other than that it LGTM!

**Comment by seocam** [comment]
> One thing caught my attention in this PR: many strings are enclosed by double quotes. Is that really needed?
> I can see it's not only code modified by this PR but in the services tests as a whole.

@rjeffman forget about this. I was mistaken and it looks good.

**Pull request merged**
