### PR TITLE
Fixes removal of `all` from categories in sudorule and hbacrule modules.

### PR DESCRIPTION
**Pull request by rjeffman**
This patch fixes removal of categories with `all` value from `sudorule` and `hbacrule` modules.

### CODE REVIEW

**Comment by seocam** [comment]
I think that if we were using a truly declarative model we wouldn't need to set an empty string. 

For example: 

In the cron module, if you define the following play:
 
```yaml
cron:
  name: "That's true"
  hour: "12"
  minute: "0"
  job: "/usr/bin/true"
```
That will result in:

```console
[scampos@ipaserver ~]$ crontab -l
#Ansible: That's true
0 12 * * * /usr/bin/true
```

By removing the minutes line and running it again:
 
```yaml
cron:
  name: "That's true"
  hour: "12"
  job: "/usr/bin/true"
```
That will result in:

```console

[scampos@ipaserver ~]$ crontab -l
#Ansible: That's true
0 12 * * * /usr/bin/true
```

In other words, IMO, our modules should be more declarative and we shouldn't need to set the empty string in order to go back to what it was. Instead we should just remove that line.

With all of that said, I also understand that this is currently not the reality for our modules, and I'm not sure if that's something we want for our modules.

If we are good with the way the modules currently work I think your implementation is totally fine @rjeffman. If not we should start talking about changing it.

**Comment by rjeffman** [comment]
Current implementation follows `cron` module idea. Setting `all` for sudorule user category now becomes:
```yaml
ipasudorule:
  name: testrule
  usercategory: all
  state: present
```
If after that we run the following script, `usercategory` would be cleared:
```yaml
ipasudorule:
  name: testrule
  state: present
```
Similar changes have been applied to `hbacrule`.

**Comment by t-woerner** [comment]
> 
> ```yaml
> ipasudorule:
>   name: testrule
>   state: present
> ```
> 

This may not clear `usercategory` at all. This task only makes sure that a sudorule with the name `testrule` exists.

**Comment by rjeffman** [comment]
Fix adds choice `""` to all `*category` fields that had only `all` to remove the attribute from the rule.

**Comment by t-woerner** [comment]
LGTM

**Pull request merged**
